import type { Metadata } from "next";
import { Geist, Geist_Mono,Dancing_Script, Merriweather, Montserrat, Host_Grotesk, Bodoni_Moda, Cormorant_Garamond, Cinzel, Marcellus } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-dancing-script',
})

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['300', '400','500','600', '700', '900'],
  style: ['normal', 'italic'],
  variable: '--font-merriweather',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--font-montserrat',
})

const hostGotek = Host_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: '--font-host-grotesk',
})

const bodoniModa = Bodoni_Moda({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: '--font-bodoni-moda',
})

const cormorantGaramond = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300','400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: '--font-cormorant-garamond',
})

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  variable: '--font-cinzel',
})

const marcellus = Marcellus({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  variable: '--font-marcellus',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marcellus.variable} ${cinzel.variable} ${cormorantGaramond.variable} ${bodoniModa.variable} ${dancingScript.variable} ${merriweather.variable} ${montserrat.variable} ${hostGotek.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
